spring:
  profiles.active: development
  datasource:
    url: jdbc:mysql://192.168.1.197:3306/wechartExam?useUnicode=true&characterEncoding=utf-8
    username: root
    password: GiveME$999
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  pidfile: shared/tmp/pids/application.pid
server:
  port: 10002
logging:
  level:
    org.springframework: 'OFF'
    com.xiaojiuwo.models.mapper: DEBUG
endpoints:
  shutdown:
    enabled: true
    sensitive: false
 
    
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wechartExam?useUnicode=true&characterEncoding=utf-8
    username: root
    password: IWantMoney@999
    driverClassName: com.mysql.jdbc.Driver

   
server:
  port: 10002
---
spring:
  profiles: localtest1
  
---
spring:
  profiles: localtest2
server:
  port: 10001
  
